Add string constant provider
soma-smart/Fakelake pull request #38
Opened 2024-03-14 20:38 UTC by bhagenbourger

Partially solves #20

2024-03-23 13:33 UTC, bhagenbourger commented
I only manage string type for the moment for string provider. I will do another PR for other types later.  
Is this what you expected for constant provider?

2024-03-23 20:46 UTC, vianneybacoup reviewed
@bhagenbourger I imagined only the part with only one value, so you went waayy further ! Thank you for this ! 👍 
I put some comments, feel free to question them if you feel they are not relevant.
I also let you rebase, there are some updates to add as well.

2024-03-23 20:46 UTC, vianneybacoup commented on tests/parquet_all_options.yaml
> +      - value: my_third_constant
Can you add all the different cases of setting data here ?
There is a test that uses both all_options.yaml file

2024-03-23 20:46 UTC, vianneybacoup commented on src/providers/provider.rs
> +    fn given_valid_provider_should_return_provider() {
Way cleaner, thanks

2024-03-24 12:55 UTC, bhagenbourger commented
Thank you for your feedback @vianneybacoup 
I think about your advice and I propose to split what I did into three providers:
 - ConstantStringProvider : a provider which accepts a single value and returns this value
 - ListStringProvider : a provider which accepts a list of values and returns a value randomly chosen
 - WeightedListStringProvider : a provider which accepts a weighted list of values and returns a value weighted randomly chosen

What do you think about that?

2024-03-24 14:06 UTC, vianneybacoup commented
> Thank you for your feedback @vianneybacoup I think about your advice and I propose to split what I did into three providers:
> 
> * ConstantStringProvider : a provider which accepts a single value and returns this value
> * ListStringProvider : a provider which accepts a list of values and returns a value randomly chosen
> * WeightedListStringProvider : a provider which accepts a weighted list of values and returns a value weighted randomly chosen
> 
> What do you think about that?

That's perfect.
This should be purely on dev side. For the user, it will access those three providers with Constant.string (like what you did already), and the new_from_yaml function will return the correct one.

2024-03-31 13:06 UTC, bhagenbourger commented on src/providers/parameters/wstring.rs
> +fn extrat_hash(
Sorry didn't see it, fixed.

2024-03-31 13:07 UTC, bhagenbourger commented on Cargo.toml
> +linked-hash-map = "0.5.6"
I didn't pay attention for alphabetical order, fixed

2024-03-31 13:08 UTC, bhagenbourger commented on src/providers/constant/string.rs
> +impl StringProvider {
Renamed. I created 3 providers like discussed.

2024-03-31 13:10 UTC, bhagenbourger commented on src/providers/constant/string.rs
> +        let max: u32 = weighted_strings.iter().map(|w| w.weight).sum::<u32>();
I asked myself when I wrote this code and I decided that the Vec has few values but definitively this code doesn't scale. I fixed it.

2024-04-08 08:44 UTC, vianneybacoup reviewed
Thanks for all the work !
Nothing too serious to change, we can push this right after

2024-04-08 08:44 UTC, vianneybacoup commented on src/providers/constant/string.rs
> +    fn corrupted_value(&self, _: u32) -> Value {
missing tests for all three corrupted_value functions

2024-04-13 16:22 UTC, vianneybacoup requested changes
I forgot that sorry

2024-04-14 12:57 UTC, bhagenbourger commented
No worries, I didn't have time to fix that sooner. I just amended my commit with the fixes.

2024-04-14 19:16 UTC, vianneybacoup approved these changes
Didn't meant to be pushy, sorry about that.
We obviously love the work you made on Fakelake :)

Approved, thanks again

2024-04-14 19:30 UTC, merged