Add external file provider
soma-smart/Fakelake pull request #46
Opened 2024-04-27 13:29 UTC by bhagenbourger

#45

2024-04-27 16:45 UTC, vianneybacoup requested changes

2024-04-27 16:45 UTC, vianneybacoup commented on src/providers/person/builder.rs
> +static LAST_NAMES_PATH: &str = "static/last_name_fr.txt";
We can't do that, now it means you can only use those two Providers with the files attached to them (and at this location as well)
Previous code stored the content of the file in the compiled version to avoid being stuck with files

Can you try to store in static the FileParameter directly ?

2024-04-28 14:31 UTC, bhagenbourger commented on src/providers/person/builder.rs
> +static LAST_NAMES_PATH: &str = "static/last_name_fr.txt";
As FileParameter expects a path, I tried another solution to fix that.
Let me know if it's ok.

2024-04-29 09:03 UTC, vianneybacoup approved these changes

2024-04-29 09:09 UTC, vianneybacoup approved these changes

2024-04-29 09:09 UTC, merged